### ISSUE TITLE
Support for HighGFX screenmodes?

### ISSUE THREAD

**Issue by Manger74** [captain-amygdala/pistorm-video-passtrough#3]
Lately i found new display drivers for the ECS/AGA chipset.

https://aminet.net/package/driver/moni/HighGFXnmore

HighGFX'n'more
a package with additional screenmodes for the classic AmigaOS (V3.0+)

800x600 SuperPlus 48Hz, 15,16kHz interlaced
1024x768 HighGFX 55Hz, 22,22kHz interlaced
1280x720 HD720 47Hz, 17,86kHz interlaced
1280x1024 XTREME 34Hz, 18,08kHz interlaced

These modes enable the ECS/AGA chipset to display the most common monitor ressolutions. Of course these screenmodes need to be flickerfixed.

Some applications like Lightwave 3D are not working properly under RTG. It would be awsome to promote Lightwave to a higher resolution planar screen.

Will the RGB 2 PiStorm support the HighGFX modes?

WINUAE supports them perfectly in it's last iteration.
Amiberry handles the SuperPlus well but still has some issues with the others.
HighGFX is supported by the Indivision AGA MKIII.

**Comment by captain-amygdala** [comment]
Hi, closing the issue. This project is not the video passthrough which gets released soon but a older development branch.
